# Generated by Django 2.1.7 on 2019-03-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('Num_Ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_de_Indicios', models.IntegerField(default=1)),
                ('Resguardo_en', models.CharField(choices=[('B', 'Boveda'), ('G', 'Bodega y/o Almacen')], default='B', max_length=1)),
                ('Carpeta_Investigacion', models.CharField(help_text='Ingrese el numero de Carpeta de Investigación', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Ingreso', models.DateField(blank=True, null=True)),
                ('Hora_Ingreso', models.TimeField(blank=True, null=True)),
                ('Oficio', models.CharField(max_length=15)),
                ('No_Indicio', models.CharField(help_text='Ingrese el numero de indicio', max_length=10)),
                ('Tipo', models.CharField(choices=[('F', 'Fisico'), ('O', 'Organico'), ('B', 'Biologico'), ('M', 'Fisico/Organico')], default='F', max_length=1)),
                ('Descripcion', models.TextField(help_text='Describe el indicio como la etiqueta', max_length=500)),
                ('Rue', models.CharField(help_text='Format = OM/F/100/2019', max_length=15)),
                ('Clasificacion', models.CharField(choices=[('AC', 'Arma de Fuego Corta'), ('AL', 'Arma de Fuego Larga'), ('AB', 'Arma Blanca'), ('EM', 'Estupefaciente-Marihuana'), ('EC', 'Estupefaciente-Cocaina'), ('EH', 'Estupefaciente-Heroina'), ('EA', 'Estupefaciente-Anfetamina'), ('ET', 'Estupefaciente-Tabaco'), ('AL', 'Alcohol'), ('P', 'Perecedero'), ('E', 'Electronico'), ('AP', 'Autopartes'), ('H', 'Herramientas'), ('AB', ' Articulos de Belleza'), ('J', 'Joyeria'), ('R', ' Ropa'), ('N', ' Numerario'), ('O', 'Otro')], default='A', max_length=2)),
                ('Deposito_Banco', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='S', max_length=1)),
                ('Cantidad', models.IntegerField(default=0)),
                ('Cadena', models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('CS', 'Copia Simple'), ('CC', 'Copia Certificada')], default='S', max_length=2)),
                ('Embalaje', models.CharField(choices=[('B', 'Bolsa de Plastico'), ('BP', 'Bolsa de Papel'), ('SB', 'Sobre Blanco'), ('SM', 'Sobre Manila'), ('EM', 'Emplayado'), ('CJ', 'Caja de Carton'), ('SE', 'Sin Embalaje'), ('O', 'Otro')], default='B', max_length=2)),
                ('Estado_embalaje', models.CharField(choices=[('C', 'Cerrado'), ('A', 'Abierto'), ('AL', 'Alterado'), ('R', 'Roto'), ('O', 'Otro')], default='C', max_length=2)),
                ('Ubicacion', models.TextField(help_text='Ingrese ubicacion del indicio', max_length=100)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='userlogo/')),
                ('Observaciones', models.TextField(help_text='Aqui puede hacer observaciones del indicio y embalaje, entre otras', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre Completo empezando por Nombre, Apellido Paterno, Apellido Materno', max_length=50)),
                ('Cargo', models.CharField(help_text='Ingrese el cargo de la Autoridad', max_length=50)),
                ('Adscripcion', models.CharField(help_text='Ingrese el lugar de Agencia o Unidad', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Movimiento', models.CharField(choices=[('ST', 'Salidad Temporal'), ('SD', 'Salida Definitiva')], default='SD', max_length=2)),
                ('Fecha_de_Movimiento', models.DateField()),
                ('Indicio_Numero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Indicio')),
                ('Quien_Recibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Mp')),
            ],
        ),
        migrations.AddField(
            model_name='indicio',
            name='Entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Mp'),
        ),
        migrations.AddField(
            model_name='indicio',
            name='Ingreso_Num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Expediente'),
        ),
    ]
