# Generated by Django 2.1.7 on 2019-03-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='Indicio_Numero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Indicio'),
        ),
    ]
