# Generated by Django 2.1.7 on 2019-03-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0002_auto_20190312_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicio',
            name='Ingreso_Num',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Expediente'),
        ),
    ]
