# Generated by Django 2.1.7 on 2019-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0003_auto_20190312_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicio',
            name='Ubicacion',
            field=models.CharField(help_text='Ingrese ubicacion del indicio', max_length=50),
        ),
    ]
