# Generated by Django 2.1.7 on 2019-03-13 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0004_auto_20190312_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicio',
            name='Dictamen',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='indicio',
            name='Fecha_Caducidad',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicio',
            name='Peso_Narcotico',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Rue',
            field=models.CharField(help_text='Formato = OM/F/100/2019', max_length=15),
        ),
    ]
