# Generated by Django 2.1.7 on 2019-03-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0006_auto_20190313_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_rue', models.IntegerField(default=530)),
            ],
        ),
    ]
