# Generated by Django 2.1.7 on 2019-03-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0007_rue'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidas',
            name='Imagen_salida',
            field=models.ImageField(blank=True, null=True, upload_to='imagensalida/'),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='Tipo_Movimiento',
            field=models.CharField(choices=[('ST', 'Salidad Temporal'), ('SD', 'Salida Definitiva'), ('TR', 'Traslado a Bodega')], default='SD', max_length=2),
        ),
    ]
