# Generated by Django 2.1.7 on 2019-03-15 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0010_auto_20190315_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicio',
            name='Ingreso_Num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Expediente'),
        ),
    ]
