# Generated by Django 2.1.7 on 2019-03-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0011_auto_20190315_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Resguardo_en',
            field=models.CharField(choices=[('B', 'Boveda'), ('A', 'Bodega y/o Almacen')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Deposito_Banco',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Fecha_Caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Observaciones',
            field=models.TextField(blank=True, help_text='Aqui puede hacer observaciones del indicio y embalaje, entre otras', max_length=200, null=True),
        ),
    ]
