# Generated by Django 2.1.7 on 2019-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0013_auto_20190327_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicio',
            name='Clasificacion',
            field=models.CharField(choices=[('AC', 'Arma de Fuego Corta'), ('AL', 'Arma de Fuego Larga'), ('AB', 'Arma Blanca'), ('EM', 'Estupefaciente-Marihuana'), ('EC', 'Estupefaciente-Cocaina'), ('EH', 'Estupefaciente-Heroina'), ('EA', 'Estupefaciente-Anfetamina'), ('EL', 'Estupefaciente-Cristal'), ('T', 'Tabaco'), ('AL', 'Alcohol'), ('P', 'Perecedero'), ('E', 'Electronico'), ('AP', 'Autopartes'), ('H', 'Herramientas'), ('AR', ' Articulos de Belleza'), ('J', 'Joyeria'), ('R', ' Ropa'), ('N', ' Numerario'), ('DC', 'Documentos'), ('MA', 'Medio de Almacenamiento'), ('M', 'Medicamento'), ('EB', 'Elemento Balistico'), ('O', 'Otro')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='Fecha_de_Movimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
