# Generated by Django 2.1.7 on 2019-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0014_auto_20190328_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicio',
            name='Cantidad',
            field=models.FloatField(default=0.0),
        ),
    ]
