# Generated by Django 2.1.7 on 2019-04-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0015_auto_20190328_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='Imagen_salida',
            field=models.ImageField(blank=True, null=True, upload_to='userlogo/'),
        ),
    ]
