# Generated by Django 2.1.7 on 2019-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0017_auto_20190401_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='Imagen_salida',
            field=models.ImageField(blank=True, null=True, upload_to='salidas/'),
        ),
    ]
