# Generated by Django 2.1.7 on 2019-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0018_auto_20190401_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expediente',
            options={'ordering': ['Carpeta_Investigacion'], 'verbose_name': 'Carpeta'},
        ),
        migrations.AlterModelOptions(
            name='indicio',
            options={'verbose_name': 'Ingreso'},
        ),
        migrations.AlterModelOptions(
            name='mp',
            options={'ordering': ['Nombre'], 'verbose_name': 'Autoridad', 'verbose_name_plural': 'Autoridades'},
        ),
        migrations.AlterModelOptions(
            name='salidas',
            options={'ordering': ['Tipo_Movimiento'], 'permissions': (('can_mark_returned', 'Regresar el Indicio'),), 'verbose_name': 'Movimiento'},
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Clasificacion',
            field=models.CharField(choices=[('AC', 'Arma de Fuego Corta'), ('AF', 'Arma de Fuego Larga'), ('PP', 'Pistola de Plastico'), ('AB', 'Arma Blanca'), ('EM', 'Estupefaciente-Marihuana'), ('EC', 'Estupefaciente-Cocaína'), ('EH', 'Estupefaciente-Heroína'), ('EA', 'Estupefaciente-Anfetamina'), ('EL', 'Estupefaciente-Cristal'), ('EL', 'Estupefaciente-LCD'), ('T', 'Tabaco'), ('AL', 'Alcohol'), ('P', 'Perecedero'), ('E', 'Electrónico'), ('AP', 'Autopartes'), ('H', 'Herramientas'), ('AR', ' Artículos de Belleza'), ('J', 'Joyeria'), ('R', ' Ropa'), ('N', ' Numerario'), ('DC', 'Documentos'), ('MA', 'Medio de Almacenamiento'), ('M', 'Medicamento'), ('EB', 'Elemento Balístico'), ('O', 'Otro')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Embalaje',
            field=models.CharField(choices=[('B', 'Bolsa de Plástico'), ('BP', 'Bolsa de Papel'), ('SB', 'Sobre Blanco'), ('SM', 'Sobre Manila'), ('EM', 'Emplayado'), ('CJ', 'Caja de Cartón'), ('SE', 'Sin Embalaje'), ('O', 'Otro')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Tipo',
            field=models.CharField(choices=[('F', 'Físico'), ('O', 'Orgánico'), ('B', 'Biológico'), ('FO', 'Físico/Orgánico')], default='F', max_length=2),
        ),
    ]
