# Generated by Django 2.1.7 on 2019-04-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0019_auto_20190402_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expediente',
            options={'verbose_name': 'Carpeta'},
        ),
        migrations.AlterField(
            model_name='indicio',
            name='Clasificacion',
            field=models.CharField(choices=[('AC', 'Arma de Fuego Corta'), ('AF', 'Arma de Fuego Larga'), ('PP', 'Pistola de Plastico'), ('AB', 'Arma Blanca'), ('EM', 'Estupefaciente-Marihuana'), ('EC', 'Estupefaciente-Cocaína'), ('EH', 'Estupefaciente-Heroína'), ('EA', 'Estupefaciente-Anfetamina'), ('ER', 'Estupefaciente-Cristal'), ('EL', 'Estupefaciente-LCD'), ('T', 'Tabaco'), ('AL', 'Alcohol'), ('P', 'Perecedero'), ('E', 'Electrónico'), ('AP', 'Autopartes'), ('H', 'Herramientas'), ('AR', ' Artículos de Belleza'), ('J', 'Joyeria'), ('R', ' Ropa'), ('N', ' Numerario'), ('DC', 'Documentos'), ('MA', 'Medio de Almacenamiento'), ('M', 'Medicamento'), ('EB', 'Elemento Balístico'), ('O', 'Otro')], default='A', max_length=2),
        ),
    ]
