# Generated by Django 2.1.7 on 2019-04-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0020_auto_20190402_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='Resguardo_en',
            field=models.CharField(choices=[('B', 'Bóveda'), ('A', 'Bodega de Bienes Asegurados')], default='B', max_length=1),
        ),
    ]
