# Generated by Django 2.1.7 on 2019-04-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0021_auto_20190402_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definitiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_de_Movimiento', models.DateField(blank=True, null=True)),
                ('Persona_Recibe', models.CharField(help_text='Ingrese Nombre de quien entrega fisicamente el indicio', max_length=50)),
                ('Imagen_salida', models.ImageField(blank=True, null=True, upload_to='definitiva/')),
                ('Autoridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Mp')),
                ('Carpeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Expediente')),
                ('Rue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Indicio')),
            ],
        ),
        migrations.CreateModel(
            name='Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_de_Movimiento', models.DateField(blank=True, null=True)),
                ('Persona_Recibe', models.CharField(help_text='Ingrese Nombre de quien entrega fisicamente el indicio', max_length=50)),
                ('Imagen_salida', models.ImageField(blank=True, null=True, upload_to='temporal/')),
                ('Autoridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Mp')),
                ('Carpeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Expediente')),
                ('Rue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Indicio')),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_de_Movimiento', models.DateField(blank=True, null=True)),
                ('Persona_Recibe', models.CharField(help_text='Ingrese Nombre de quien entrega fisicamente el indicio', max_length=50)),
                ('Imagen_salida', models.ImageField(blank=True, null=True, upload_to='traslado/')),
                ('Carpeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Expediente')),
                ('Quien_Recibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Mp')),
                ('Rue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boveda.Indicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='Indicio_Numero',
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='Quien_Recibe',
        ),
        migrations.DeleteModel(
            name='Salidas',
        ),
    ]
