# Generated by Django 2.1.7 on 2019-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0022_auto_20190410_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traslado',
            old_name='Quien_Recibe',
            new_name='Autoridad',
        ),
        migrations.AlterField(
            model_name='definitiva',
            name='Persona_Recibe',
            field=models.CharField(help_text='Ingrese Nombre de quien recibe fisicamente el indicio', max_length=50),
        ),
        migrations.AlterField(
            model_name='temporal',
            name='Persona_Recibe',
            field=models.CharField(help_text='Ingrese Nombre de quien recibe fisicamente el indicio', max_length=50),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='Persona_Recibe',
            field=models.CharField(help_text='Ingrese Nombre de quien recibe fisicamente el indicio', max_length=50),
        ),
    ]
