# Generated by Django 2.1.7 on 2019-04-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boveda', '0023_auto_20190411_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='definitiva',
            name='Oficio',
            field=models.CharField(blank=True, help_text='Ingrese el número de Oficio', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='definitiva',
            name='Sasca',
            field=models.CharField(blank=True, help_text='Ingrese el número de Sasca', max_length=10, null=True),
        ),
    ]
